/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package swing1;

import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.*;


import java.util.*;
import javax.swing.JFrame;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.JPasswordField;
import java.awt.BorderLayout;
import java.awt.Container;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class AppTest {
    private UserAdmin StartScreen;
    private JButton userClick;
    private JButton adminClick;
    @BeforeEach public void setUpApp() {
        //AppTest a = new AppTest();
        this.userClick = new JButton("User");
        this.adminClick = new JButton("Admin");
        this.StartScreen = new UserAdmin(userClick, adminClick);
    }
    @Test public void testStartScreen() {
        assertNotNull(this.StartScreen);
        assertTrue(this.StartScreen.isVisible);
    }
    @Test public void testAdminClick() {
        ActionEvent a = new ActionEvent(this.adminClick,ActionEvent.ACTION_PERFORMED,null);
        StartScreen.actionPerformed(a);
        assertNotNull(this.StartScreen);
        assertFalse(this.StartScreen.isVisible);
    }
    @Test public void testUserClick() {
        ActionEvent a = new ActionEvent(this.userClick,ActionEvent.ACTION_PERFORMED,null);
        StartScreen.actionPerformed(a);
        assertNotNull(this.StartScreen);
        assertFalse(this.StartScreen.isVisible);
    }
    @Test public void testAdminPassword() {
        ActionEvent a = new ActionEvent(this.adminClick,ActionEvent.ACTION_PERFORMED,null);
        StartScreen.actionPerformed(a);
        ActionEvent b = new ActionEvent(this.StartScreen.password.adminPassword,ActionEvent.ACTION_PERFORMED,null);
        StartScreen.actionPerformed(b);
        assertNotNull(this.StartScreen);
        assertFalse(this.StartScreen.isVisible);
    }
    @Test public void testPasswordCheckerCorrect() {
        char[] correctPassword = {'s','o','f','t','2','4','1','2'};
        this.StartScreen.password.passwordChecker(correctPassword);
        assertFalse(this.StartScreen.password.isVisible);
    }
    @Test public void testPasswordCheckerWrong() {
        char[] wrongPassword = {'n','o','2','2','3','0','2','4','a'};
        this.StartScreen.password.passwordChecker(wrongPassword);
        assertTrue(this.StartScreen.password.isVisible);
    }
    @Test public void testPasswordCheckerAnotherCase() {
        char[] wrongPassword = {'a'};
        this.StartScreen.password.passwordChecker(wrongPassword);
        assertTrue(this.StartScreen.password.isVisible);
    }
    @Test public void testPasswordCheckerAnotherCase2() {
        char[] wrongPassword = {'0','0','0'};
        this.StartScreen.password.passwordChecker(wrongPassword);
        assertTrue(this.StartScreen.password.isVisible);
    }
    @Test public void testPasswordCheckerAnotherCase3() {
        char[] wrongPassword = {'f','f','d','d','g'};
        this.StartScreen.password.passwordChecker(wrongPassword);
        assertFalse(this.StartScreen.password.isVisible);
    }
}

